In [1]:
numpy
=====


In [2]:
L=[10,20,30]  # List - collection of items(different type)
L+100

TypeError: can only concatenate list (not "int") to list

In [3]:
L1=[1,2,3,4]
L2=[5,6,7,8]
L1+L2

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
import array
array.array('i',[1,2,3])

array('i', [1, 2, 3])

In [5]:
a1=array.array('i',[1,2,3])
a1[0]

1

In [6]:
a1[1]

2

In [7]:
a1.append(40)
a1

array('i', [1, 2, 3, 40])

In [8]:
a1.append('data')


TypeError: 'str' object cannot be interpreted as an integer

In [9]:
a1.append(2.6)

TypeError: 'float' object cannot be interpreted as an integer

In [10]:
a1= array.array('i',[1,2,3])
a2=array.array('i',[10,20,30])
a1+a2 # Like List concatenate

array('i', [1, 2, 3, 10, 20, 30])

In [ ]:
python.org--> python + std libraries 
--------------------------------------------> pip install numpy

In [ ]:
import numpy

# numpy array index, slicing, shape, reshape,dim
# numpy functions


In [11]:
numpy.array([10,20,30])

array([10, 20, 30])

In [12]:
numpy.array([10,20,30,40.0])

array([10., 20., 30., 40.])

In [13]:
numpy.array([10,20,30,'data',True])

array(['10', '20', '30', 'data', 'True'], dtype='<U21')

In [15]:
numpy.array([10,20,30,True,False])

array([10, 20, 30,  1,  0])

In [16]:
arr=numpy.array([10,20,30])
arr+ 100

array([110, 120, 130])

In [17]:
arr=numpy.array([10,20,30])
arr*0.12

array([1.2, 2.4, 3.6])

In [18]:
arr1=numpy.array([10,20,30])
arr2=numpy.array([100,200,300])
arr1+arr2

array([110, 220, 330])

In [20]:
arr1=numpy.array([10,20,30])
arr2=numpy.array([100,200,300])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / 5)
print(arr1 ** 2)

[110 220 330]
[ -90 -180 -270]
[1000 4000 9000]
[2. 4. 6.]
[100 400 900]


In [21]:
numpy.array([10,20,30]) +100

array([110, 120, 130])

In [22]:
numpy.array([10,20,30]) + numpy.array([10,20,30,40])

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [23]:
numpy.array([10,20,30,40]) < numpy.array([100,200,300,400])

array([ True,  True,  True,  True])

In [24]:
numpy.array([10,20,30,40]) > numpy.array([100,200,300,400])

array([False, False, False, False])

In [25]:
numpy.array([10,20,30,40]) > 35

array([False, False, False,  True])

In [27]:
import array
array.array('i',[1,2,3,4])  # single dim

array('i', [1, 2, 3, 4])

In [28]:
array.array('i',[[1,2,3,4]])

TypeError: 'list' object cannot be interpreted as an integer

In [30]:
import numpy
numpy.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [33]:
arr1=numpy.array([1,2,3,4])
arr2=numpy.array([[100,200,300,400]])
print(arr1,arr2)
print(arr1.ndim, arr2.ndim)

[1 2 3 4] [[100 200 300 400]]
1 2


In [34]:
arr2=numpy.array([[[100,200,300,400]]])
print(arr2)
print(arr2.ndim)

[[[100 200 300 400]]]
3


In [35]:
numpy.array([[[[[[[[[[]]]]]]]]]]).ndim

10

In [38]:
#shape -> tuple(rows,cols)

a1= numpy.array([10,20,30,40])   
a2= numpy.array([[10,20,30,40]])   
a3= numpy.array([[[10,20,30,40]]]) 
print(a1.shape)
print(a2.shape)
print(a3.shape)


(4,)
(1, 4)
(1, 1, 4)


In [ ]:
#|col1||col2|....|coln|-> R1||  R2 

In [40]:
a3= numpy.array([[[10,20,30],[40,50,60]]]) 
print(a3.ndim,a3.shape)

3 (1, 2, 3)


In [41]:
a3= numpy.array([[[10,20,30],[40,50,60],[70,10,20],[40,90,1]]]) 
print(a3.ndim,a3.shape)

3 (1, 4, 3)


In [42]:
a3= numpy.array([[[10,20,30],[40,50,60],[70,10,20],[40,90,1]]]) 
print(a3[0])

[[10 20 30]
 [40 50 60]
 [70 10 20]
 [40 90  1]]


In [43]:
a3= numpy.array([[[10,20,30],[40,50,60],[70,10,20],[40,90,1]]]) 
print(a3[0][0])

[10 20 30]


In [44]:
a3= numpy.array([[[10,20,30],[40,50,60],[70,10,20],[40,90,1]]]) 
print(a3[0][0][0])

10


In [45]:
a3= numpy.array([[[10,20,30],[40,50,60],[70,10,20],[40,90,1]]]) 
print(a3[0][0][0])
print(a3[0][0][1])
print(a3[0][0][-1])

10
20
30


In [47]:
print(a3[0][1])

[40 50 60]


In [48]:
print(a3[0][1][0])

40


In [49]:
range(5)

range(0, 5)

In [50]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [51]:
np.random.rand()  

0.4792917105212193

In [53]:
np.random.randint(10)  

6

In [57]:
np.random.randint(5,15,3)  #any 3 random nos

array([11,  7, 14], dtype=int32)

In [58]:
np.zeros(5) # generate 1 dim array with zeros

array([0., 0., 0., 0., 0.])

In [59]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [60]:
np.asarray([10,20,30], dtype=float)

array([10., 20., 30.])

In [62]:
a1= np.array([[10,20,30],[40,50,60]])
print(type(a1))
print(a1.ndim)
print(a1.shape)

<class 'numpy.ndarray'>
2
(2, 3)


In [63]:
np.asarray([[10,20,30],[40,50,60]],dtype=float)

array([[10., 20., 30.],
       [40., 50., 60.]])

In [64]:
a1= np.array([[10,20,30],[40,50,60]])
np.reshape(a1,(3,2))

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
np.add(a1,a2)  --> np.a1 +np.a2
np.less(a1,a2)  -->  np.a1  < np.a2
np.greater(a1,a2)  --> np.a1 > np.a2


In [ ]:
# statistical functions
np.median()
np.mean()
np.std()


In [67]:
np.median([10,20,30,4,40,50,60])

np.float64(30.0)

In [69]:
np.mean([10,20,30,4,40,50,60])

np.float64(30.571428571428573)

In [71]:
a2=np.array([[10,20,30],[40,50,60]])
a2.ndim            

2

In [72]:
a2.flatten()

array([10, 20, 30, 40, 50, 60])

In [73]:
a2.dtype

dtype('int64')

In [74]:
np.array([10,20,30.0]).dtype

dtype('float64')

In [75]:
np.array([10,20,'30.0']).dtype

dtype('<U21')

In [77]:
np.array([10,20,True,False]).dtype

dtype('int64')

In [78]:
np.array([True,False]).dtype

dtype('bool')

In [79]:
print(np.array([10,20,30]))  # int32/64
# vs
np.array([10,20,30],dtype='float')

[10 20 30]


array([10., 20., 30.])